name: Mirror to Codeberg

on:
  push:
    branches:
      - main   # change if your default branch is different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for full mirror

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEBERG_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Mirror push to Codeberg
        run: |
          git remote add codeberg git@codeberg.org:DavidBalishyan/betterfetch.git
          git push --mirror codeberg

